# Generated by Django 4.0.4 on 2022-05-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIRGANI_Badreddine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
