# Generated by Django 4.0.4 on 2022-05-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TIRGANI_Badreddine', '0002_alter_personne_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personne',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
